# argo-cd/envs/dev/argocd-rbac-cm-patch.yaml
apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: argocd-rbac-cm  
  namespace: argocd  
data:  
  policy.csv: |  
    g, devbcn, role:devbcn-demo-admin  
  policy.default: role:readonly  
  scopes: '[groups]'  
policy.roles: |  
  # deny all global configuration actions  
  p, role:devbcn-demo-admin, *, *, *, deny  
  # allow full application access only within devbcn-demo project  
  p, role:devbcn-demo-admin, applications, *, devbcn-demo/*, allow  
  # allow read access to project details (recommended)  
  p, role:devbcn-demo-admin, projects, get, devbcn-demo, allow